import type { Activity, Category, Destination, PriceTier, TimeOfDay } from './types'

export const CITY = 'Santa Monica'

export const CATEGORY_META: Record<Category, { label: string; emoji: string; hue: string }> = {
  outdoors: { label: 'Outdoors', emoji: '🌿', hue: 'lagoon' },
  water: { label: 'On the water', emoji: '🌊', hue: 'lagoon' },
  food: { label: 'Food & drink', emoji: '🍋', hue: 'sun' },
  wellness: { label: 'Wellness', emoji: '🌸', hue: 'bloom' },
  culture: { label: 'Culture', emoji: '🖼️', hue: 'bloom' },
  nightlife: { label: 'Nightlife', emoji: '🌅', hue: 'bloom' },
  creative: { label: 'Creative', emoji: '🎨', hue: 'sun' },
  market: { label: 'Markets', emoji: '🧺', hue: 'sun' },
}

export const TIME_OF_DAY_META: Record<TimeOfDay, { label: string; window: string }> = {
  morning: { label: 'Morning', window: '6am – 12pm' },
  afternoon: { label: 'Afternoon', window: '12pm – 5pm' },
  evening: { label: 'Evening', window: '5pm – late' },
}

export const PRICE_TIER_LABEL: Record<PriceTier, string> = {
  0: 'Free',
  1: '$',
  2: '$$',
  3: '$$$',
}

export const ACTIVITIES: Activity[] = [
  {
    id: 'a-sunrise-hike',
    title: 'Sunrise hike up Temescal Ridge',
    place: 'Temescal Canyon',
    neighborhood: 'Pacific Palisades',
    blurb:
      'Ninety minutes up a fern-lined canyon that opens onto the whole bay just as the light turns gold.',
    category: 'outdoors',
    priceTier: 0,
    price: 0,
    durationMin: 105,
    rating: 4.8,
    reviewCount: 1204,
    distanceKm: 6.4,
    timeOfDay: ['morning'],
    outdoor: true,
    tags: ['sunrise', 'views', 'moderate climb'],
    seed: 11,
  },
  {
    id: 'a-tidepools',
    title: 'Low-tide tidepool wander',
    place: 'Leo Carrillo State Beach',
    neighborhood: 'Malibu',
    blurb:
      'Anemones, purple urchins and the occasional octopus, all in the hour either side of low tide.',
    category: 'water',
    priceTier: 1,
    price: 12,
    durationMin: 90,
    rating: 4.6,
    reviewCount: 388,
    distanceKm: 28.1,
    timeOfDay: ['morning', 'afternoon'],
    outdoor: true,
    tags: ['tide-dependent', 'family friendly', 'wildlife'],
    seed: 27,
  },
  {
    id: 'a-farmers-market',
    title: "Saturday farmers' market crawl",
    place: 'Arizona Ave Market',
    neighborhood: 'Downtown Santa Monica',
    blurb:
      'Eighty stalls of stone fruit, sourdough and cut dahlias. Come hungry, leave with flowers.',
    category: 'market',
    priceTier: 1,
    price: 25,
    durationMin: 75,
    rating: 4.9,
    reviewCount: 2611,
    distanceKm: 1.2,
    timeOfDay: ['morning'],
    outdoor: true,
    tags: ['flowers', 'produce', 'walkable'],
    seed: 5,
  },
  {
    id: 'a-surf-lesson',
    title: 'Beginner surf lesson',
    place: 'Surf Academy',
    neighborhood: 'Venice Breakwater',
    blurb: 'Two hours, soft-top boards, and a coach who will absolutely get you standing up.',
    category: 'water',
    priceTier: 2,
    price: 85,
    durationMin: 120,
    rating: 4.7,
    reviewCount: 946,
    distanceKm: 3.8,
    timeOfDay: ['morning', 'afternoon'],
    outdoor: true,
    tags: ['gear included', 'beginner', 'wetsuit'],
    seed: 41,
  },
  {
    id: 'a-citrus-breakfast',
    title: 'Citrus and ricotta breakfast',
    place: 'Maru Coffee',
    neighborhood: 'Ocean Park',
    blurb: 'Whipped ricotta toast under a mountain of blood orange. The patio gets sun until noon.',
    category: 'food',
    priceTier: 1,
    price: 22,
    durationMin: 45,
    rating: 4.5,
    reviewCount: 712,
    distanceKm: 2.1,
    timeOfDay: ['morning'],
    outdoor: true,
    tags: ['patio', 'coffee', 'vegetarian'],
    seed: 63,
  },
  {
    id: 'a-rose-garden',
    title: 'Rose garden slow loop',
    place: 'Exposition Rose Garden',
    neighborhood: 'Exposition Park',
    blurb: 'Twenty thousand roses in a sunken oval. Peak bloom smells absurd. Free, always.',
    category: 'outdoors',
    priceTier: 0,
    price: 0,
    durationMin: 60,
    rating: 4.7,
    reviewCount: 1533,
    distanceKm: 18.6,
    timeOfDay: ['morning', 'afternoon'],
    outdoor: true,
    tags: ['flowers', 'free', 'stroller friendly'],
    seed: 8,
  },
  {
    id: 'a-pottery',
    title: 'Wheel-throwing for two',
    place: 'Sunbird Ceramics',
    neighborhood: 'Mar Vista',
    blurb: 'Make two wobbly bowls, glaze them in whatever yellow you like, pick them up in a month.',
    category: 'creative',
    priceTier: 2,
    price: 95,
    durationMin: 150,
    rating: 4.9,
    reviewCount: 274,
    distanceKm: 5.5,
    timeOfDay: ['afternoon', 'evening'],
    outdoor: false,
    tags: ['date idea', 'hands on', 'all materials'],
    seed: 34,
  },
  {
    id: 'a-getty-villa',
    title: 'Getty Villa gardens and galleries',
    place: 'Getty Villa',
    neighborhood: 'Pacific Palisades',
    blurb:
      'A Roman country house rebuilt above the Pacific, with herb gardens and a reflecting pool.',
    category: 'culture',
    priceTier: 0,
    price: 0,
    durationMin: 180,
    rating: 4.8,
    reviewCount: 4102,
    distanceKm: 9.7,
    timeOfDay: ['morning', 'afternoon'],
    outdoor: true,
    tags: ['free entry', 'timed ticket', 'gardens'],
    seed: 19,
  },
  {
    id: 'a-bike-strand',
    title: 'Beach cruiser down the Strand',
    place: 'Perry’s Rentals',
    neighborhood: 'Santa Monica Pier',
    blurb: 'Twenty-two flat miles of coastline path. Rent a cruiser, ride until you want a taco.',
    category: 'outdoors',
    priceTier: 1,
    price: 18,
    durationMin: 120,
    rating: 4.4,
    reviewCount: 1877,
    distanceKm: 0.9,
    timeOfDay: ['morning', 'afternoon'],
    outdoor: true,
    tags: ['rental', 'flat route', 'ocean views'],
    seed: 52,
  },
  {
    id: 'a-sauna-plunge',
    title: 'Seaside sauna and cold plunge',
    place: 'Salt House',
    neighborhood: 'Ocean Park',
    blurb: 'Cedar barrel sauna facing the water, then a 4°C plunge, then repeat until blissed out.',
    category: 'wellness',
    priceTier: 2,
    price: 68,
    durationMin: 90,
    rating: 4.6,
    reviewCount: 431,
    distanceKm: 2.4,
    timeOfDay: ['morning', 'afternoon', 'evening'],
    outdoor: true,
    tags: ['towels included', 'book ahead', 'recovery'],
    seed: 71,
  },
  {
    id: 'a-oyster-happy-hour',
    title: 'Dollar oysters at golden hour',
    place: 'The Albright',
    neighborhood: 'Santa Monica Pier',
    blurb: 'A dozen cold oysters and a glass of something crisp, with the sun going down behind them.',
    category: 'food',
    priceTier: 2,
    price: 42,
    durationMin: 75,
    rating: 4.5,
    reviewCount: 1288,
    distanceKm: 1.0,
    timeOfDay: ['evening'],
    outdoor: true,
    tags: ['happy hour', 'seafood', 'sunset'],
    seed: 90,
  },
  {
    id: 'a-rooftop-flowers',
    title: 'Rooftop flower arranging',
    place: 'Bloomwild Studio',
    neighborhood: 'Downtown Santa Monica',
    blurb:
      'Build your own market bouquet on a rooftop full of buckets of ranunculus. Wine while you clip.',
    category: 'creative',
    priceTier: 2,
    price: 74,
    durationMin: 105,
    rating: 4.9,
    reviewCount: 196,
    distanceKm: 1.5,
    timeOfDay: ['afternoon', 'evening'],
    outdoor: true,
    tags: ['flowers', 'byo nothing', 'take it home'],
    seed: 3,
  },
  {
    id: 'a-outdoor-cinema',
    title: 'Rooftop cinema under the stars',
    place: 'Level 8 Rooftop',
    neighborhood: 'Culver City',
    blurb: 'Deck chairs, blankets, and a slightly old film projected onto a very big wall.',
    category: 'nightlife',
    priceTier: 2,
    price: 29,
    durationMin: 150,
    rating: 4.3,
    reviewCount: 604,
    distanceKm: 8.9,
    timeOfDay: ['evening'],
    outdoor: true,
    tags: ['blankets provided', 'bar', 'date idea'],
    seed: 46,
  },
  {
    id: 'a-yoga-sand',
    title: 'Sunrise yoga on the sand',
    place: 'Tower 26',
    neighborhood: 'Santa Monica Beach',
    blurb: 'Donation-based flow on the beach. Bring a towel; the mats do not love wet sand.',
    category: 'wellness',
    priceTier: 0,
    price: 0,
    durationMin: 60,
    rating: 4.7,
    reviewCount: 852,
    distanceKm: 1.1,
    timeOfDay: ['morning'],
    outdoor: true,
    tags: ['donation based', 'all levels', 'sunrise'],
    seed: 22,
  },
  {
    id: 'a-taco-crawl',
    title: 'Three-stop taco crawl',
    place: 'Various',
    neighborhood: 'Venice',
    blurb: 'Al pastor, then fish, then a birria that will ruin the others for you. Walk between.',
    category: 'food',
    priceTier: 1,
    price: 30,
    durationMin: 120,
    rating: 4.8,
    reviewCount: 967,
    distanceKm: 4.2,
    timeOfDay: ['afternoon', 'evening'],
    outdoor: true,
    tags: ['walkable', 'guided', 'spicy'],
    seed: 58,
  },
  {
    id: 'a-kayak-sunset',
    title: 'Sunset kayak through the marina',
    place: 'Marina Paddle',
    neighborhood: 'Marina del Rey',
    blurb: 'Glassy water, sea lions barking off the docks, and the sky doing something ridiculous.',
    category: 'water',
    priceTier: 2,
    price: 58,
    durationMin: 105,
    rating: 4.7,
    reviewCount: 512,
    distanceKm: 7.3,
    timeOfDay: ['evening'],
    outdoor: true,
    tags: ['sunset', 'no experience needed', 'sea lions'],
    seed: 66,
  },
  {
    id: 'a-record-shop',
    title: 'Dig through the dollar bins',
    place: 'Sunbeam Records',
    neighborhood: 'Ocean Park',
    blurb: 'Two rooms of vinyl, a resident cat, and a staff that will absolutely judge your picks.',
    category: 'culture',
    priceTier: 1,
    price: 15,
    durationMin: 60,
    rating: 4.6,
    reviewCount: 341,
    distanceKm: 2.6,
    timeOfDay: ['afternoon'],
    outdoor: false,
    tags: ['indoors', 'rainy day', 'cat'],
    seed: 37,
  },
  {
    id: 'a-botanical-glasshouse',
    title: 'Glasshouse and cactus garden',
    place: 'Huntington Gardens',
    neighborhood: 'San Marino',
    blurb: 'Sixteen themed gardens. The desert garden at 4pm is the single best light in the county.',
    category: 'outdoors',
    priceTier: 2,
    price: 35,
    durationMin: 210,
    rating: 4.9,
    reviewCount: 5230,
    distanceKm: 38.4,
    timeOfDay: ['morning', 'afternoon'],
    outdoor: true,
    tags: ['flowers', 'big walk', 'book ahead'],
    seed: 14,
  },
  {
    id: 'a-natural-wine',
    title: 'Natural wine on a side street',
    place: 'Ariel Wine Bar',
    neighborhood: 'Frogtown',
    blurb: 'Skin-contact everything, a very short menu, and candlelight by about seven.',
    category: 'nightlife',
    priceTier: 3,
    price: 110,
    durationMin: 120,
    rating: 4.6,
    reviewCount: 728,
    distanceKm: 21.5,
    timeOfDay: ['evening'],
    outdoor: false,
    tags: ['walk-ins', 'small plates', 'candlelit'],
    seed: 84,
  },
  {
    id: 'a-observatory',
    title: 'Planet-spotting at the observatory',
    place: 'Griffith Observatory',
    neighborhood: 'Griffith Park',
    blurb: 'Free telescopes on the lawn whenever it is clear, plus the whole city glittering below.',
    category: 'culture',
    priceTier: 0,
    price: 0,
    durationMin: 120,
    rating: 4.8,
    reviewCount: 8814,
    distanceKm: 24.9,
    timeOfDay: ['evening'],
    outdoor: true,
    tags: ['free', 'telescopes', 'city views'],
    seed: 77,
  },
  {
    id: 'a-hot-springs',
    title: 'Afternoon at the mineral baths',
    place: 'Sycamore Mineral Springs',
    neighborhood: 'Topanga',
    blurb: 'A private hillside tub fed by hot mineral water, surrounded by oaks and absolute quiet.',
    category: 'wellness',
    priceTier: 3,
    price: 145,
    durationMin: 120,
    rating: 4.8,
    reviewCount: 389,
    distanceKm: 16.2,
    timeOfDay: ['afternoon', 'evening'],
    outdoor: true,
    tags: ['private tub', 'book ahead', 'very quiet'],
    seed: 30,
  },
  {
    id: 'a-night-market',
    title: 'Friday night food market',
    place: 'Smorgasburg LA',
    neighborhood: 'Downtown LA',
    blurb: 'Ninety vendors, string lights, and a line for the mango soft serve that is worth it.',
    category: 'market',
    priceTier: 1,
    price: 28,
    durationMin: 120,
    rating: 4.5,
    reviewCount: 3096,
    distanceKm: 22.8,
    timeOfDay: ['evening'],
    outdoor: true,
    tags: ['string lights', 'cash and card', 'busy'],
    seed: 49,
  },
  {
    id: 'a-life-drawing',
    title: 'Life drawing, no experience needed',
    place: 'Marigold Atelier',
    neighborhood: 'Santa Monica',
    blurb: 'Charcoal, newsprint, a model and two hours of nobody looking at your paper.',
    category: 'creative',
    priceTier: 1,
    price: 25,
    durationMin: 120,
    rating: 4.7,
    reviewCount: 158,
    distanceKm: 1.8,
    timeOfDay: ['evening'],
    outdoor: false,
    tags: ['materials included', 'indoors', 'quiet'],
    seed: 61,
  },
  {
    id: 'a-pier-ferris',
    title: 'Ferris wheel at dusk',
    place: 'Pacific Park',
    neighborhood: 'Santa Monica Pier',
    blurb: 'Nine dollars and eight minutes for the best cheap view of the coastline there is.',
    category: 'outdoors',
    priceTier: 1,
    price: 9,
    durationMin: 30,
    rating: 4.2,
    reviewCount: 4471,
    distanceKm: 1.0,
    timeOfDay: ['afternoon', 'evening'],
    outdoor: true,
    tags: ['quick', 'views', 'touristy but good'],
    seed: 95,
  },
]

export const DESTINATIONS: Destination[] = [
  {
    id: 'd-amalfi',
    name: 'Praiano',
    region: 'Amalfi Coast',
    country: 'Italy',
    blurb:
      'Lemon terraces stacked above the water, and far fewer day-trippers than Positano next door.',
    nightlyFrom: 210,
    flightHours: 13,
    bestMonths: 'May – Jun, Sep',
    avgTempC: 26,
    rating: 4.9,
    reviewCount: 1840,
    vibes: ['lemon groves', 'cliff swimming', 'slow dinners'],
    seed: 7,
  },
  {
    id: 'd-tulum',
    name: 'Tulum',
    region: 'Quintana Roo',
    country: 'Mexico',
    blurb: 'Cenotes in the morning, hammock in the afternoon, grilled fish and mezcal after dark.',
    nightlyFrom: 165,
    flightHours: 5,
    bestMonths: 'Nov – Apr',
    avgTempC: 29,
    rating: 4.5,
    reviewCount: 3210,
    vibes: ['cenotes', 'beach clubs', 'ruins'],
    seed: 24,
  },
  {
    id: 'd-santorini',
    name: 'Oia',
    region: 'Santorini',
    country: 'Greece',
    blurb: 'The sunset everyone photographs, plus a caldera swim that almost nobody bothers with.',
    nightlyFrom: 290,
    flightHours: 15,
    bestMonths: 'Apr – Jun, Sep – Oct',
    avgTempC: 27,
    rating: 4.7,
    reviewCount: 5104,
    vibes: ['sunsets', 'whitewash', 'caldera swims'],
    seed: 42,
  },
  {
    id: 'd-kauai',
    name: 'Hanalei',
    region: 'Kauai',
    country: 'Hawaii',
    blurb: 'A green bay ringed by waterfalls, one main road, and plumeria on absolutely everything.',
    nightlyFrom: 245,
    flightHours: 6,
    bestMonths: 'Apr – Jun, Sep',
    avgTempC: 27,
    rating: 4.8,
    reviewCount: 2277,
    vibes: ['waterfalls', 'plumeria', 'longboards'],
    seed: 15,
  },
  {
    id: 'd-lisbon',
    name: 'Comporta',
    region: 'Alentejo',
    country: 'Portugal',
    blurb: 'Rice paddies, pine forest and eleven miles of empty Atlantic beach an hour from Lisbon.',
    nightlyFrom: 180,
    flightHours: 12,
    bestMonths: 'Jun – Sep',
    avgTempC: 25,
    rating: 4.6,
    reviewCount: 890,
    vibes: ['empty beaches', 'pine forest', 'thatched roofs'],
    seed: 55,
  },
  {
    id: 'd-bali',
    name: 'Sidemen',
    region: 'Bali',
    country: 'Indonesia',
    blurb: 'Terraced rice valleys under a volcano, frangipani everywhere, and mornings full of mist.',
    nightlyFrom: 85,
    flightHours: 21,
    bestMonths: 'Apr – Oct',
    avgTempC: 28,
    rating: 4.7,
    reviewCount: 1622,
    vibes: ['rice terraces', 'frangipani', 'volcano views'],
    seed: 68,
  },
  {
    id: 'd-cartagena',
    name: 'Cartagena',
    region: 'Bolívar',
    country: 'Colombia',
    blurb: 'A walled old town painted in mango and rose, with bougainvillea spilling off the balconies.',
    nightlyFrom: 120,
    flightHours: 8,
    bestMonths: 'Dec – Apr',
    avgTempC: 31,
    rating: 4.6,
    reviewCount: 1988,
    vibes: ['bougainvillea', 'colonial streets', 'rooftop bars'],
    seed: 33,
  },
  {
    id: 'd-byron',
    name: 'Byron Bay',
    region: 'New South Wales',
    country: 'Australia',
    blurb: 'Long right-hand point breaks, a lighthouse walk at dawn, and a very committed juice scene.',
    nightlyFrom: 200,
    flightHours: 17,
    bestMonths: 'Sep – Nov, Mar – May',
    avgTempC: 26,
    rating: 4.5,
    reviewCount: 1455,
    vibes: ['point break', 'lighthouse walk', 'markets'],
    seed: 81,
  },
  {
    id: 'd-cinque',
    name: 'Monterosso',
    region: 'Cinque Terre',
    country: 'Italy',
    blurb: 'The only one of the five with a real beach, plus anchovies and a very cold white wine.',
    nightlyFrom: 175,
    flightHours: 14,
    bestMonths: 'May – Jun, Sep',
    avgTempC: 25,
    rating: 4.6,
    reviewCount: 2640,
    vibes: ['coastal trail', 'pastel houses', 'anchovies'],
    seed: 92,
  },
  {
    id: 'd-zanzibar',
    name: 'Paje',
    region: 'Zanzibar',
    country: 'Tanzania',
    blurb: 'Turquoise shallows that go out forever, kite surfers, and frangipani in every doorway.',
    nightlyFrom: 95,
    flightHours: 22,
    bestMonths: 'Jun – Oct',
    avgTempC: 29,
    rating: 4.6,
    reviewCount: 1120,
    vibes: ['turquoise shallows', 'kitesurfing', 'spice farms'],
    seed: 47,
  },
]

export const ACTIVITY_BY_ID = new Map(ACTIVITIES.map((a) => [a.id, a]))

/** A pre-planned day so Today has something to show on first load. */
export const STARTER_DAY = [
  { id: 's-1', activityId: 'a-yoga-sand', startMin: 6 * 60 + 30 },
  { id: 's-2', activityId: 'a-citrus-breakfast', startMin: 8 * 60 },
  { id: 's-3', activityId: 'a-farmers-market', startMin: 9 * 60 + 30 },
  { id: 's-4', activityId: 'a-surf-lesson', startMin: 12 * 60 },
  { id: 's-5', activityId: 'a-rooftop-flowers', startMin: 15 * 60 + 30 },
  { id: 's-6', activityId: 'a-oyster-happy-hour', startMin: 18 * 60 + 30 },
]
