import type { Category, Destination } from './types'

export const CATEGORY_META: Record<Category, { label: string; emoji: string; hue: string }> = {
  outdoors: { label: 'Outdoors', emoji: '🌿', hue: 'lagoon' },
  water: { label: 'On the water', emoji: '🌊', hue: 'lagoon' },
  food: { label: 'Food & drink', emoji: '🍋', hue: 'sun' },
  wellness: { label: 'Wellness', emoji: '🌸', hue: 'bloom' },
  culture: { label: 'Culture', emoji: '🖼️', hue: 'bloom' },
  nightlife: { label: 'Nightlife', emoji: '🌅', hue: 'bloom' },
  creative: { label: 'Creative', emoji: '🎨', hue: 'sun' },
  market: { label: 'Markets', emoji: '🧺', hue: 'sun' },
  fun: { label: 'Fun & games', emoji: '🎡', hue: 'bloom' },
}

/**
 * What the Fun tab shows. An editorial grouping over the categories rather than
 * a separate fetch, so switching tabs is instant and costs no extra requests.
 */
export const FUN_CATEGORIES: Category[] = ['fun', 'nightlife', 'creative', 'water']

export const DESTINATIONS: Destination[] = [
  {
    id: 'd-amalfi',
    name: 'Praiano',
    region: 'Amalfi Coast',
    country: 'Italy',
    blurb:
      'Lemon terraces stacked above the water, and far fewer day-trippers than Positano next door.',
    nightlyFrom: 210,
    flightHours: 13,
    bestMonths: 'May – Jun, Sep',
    avgTempC: 26,
    rating: 4.9,
    reviewCount: 1840,
    vibes: ['lemon groves', 'cliff swimming', 'slow dinners'],
    seed: 7,
  },
  {
    id: 'd-tulum',
    name: 'Tulum',
    region: 'Quintana Roo',
    country: 'Mexico',
    blurb: 'Cenotes in the morning, hammock in the afternoon, grilled fish and mezcal after dark.',
    nightlyFrom: 165,
    flightHours: 5,
    bestMonths: 'Nov – Apr',
    avgTempC: 29,
    rating: 4.5,
    reviewCount: 3210,
    vibes: ['cenotes', 'beach clubs', 'ruins'],
    seed: 24,
  },
  {
    id: 'd-santorini',
    name: 'Oia',
    region: 'Santorini',
    country: 'Greece',
    blurb: 'The sunset everyone photographs, plus a caldera swim that almost nobody bothers with.',
    nightlyFrom: 290,
    flightHours: 15,
    bestMonths: 'Apr – Jun, Sep – Oct',
    avgTempC: 27,
    rating: 4.7,
    reviewCount: 5104,
    vibes: ['sunsets', 'whitewash', 'caldera swims'],
    seed: 42,
  },
  {
    id: 'd-kauai',
    name: 'Hanalei',
    region: 'Kauai',
    country: 'Hawaii',
    blurb: 'A green bay ringed by waterfalls, one main road, and plumeria on absolutely everything.',
    nightlyFrom: 245,
    flightHours: 6,
    bestMonths: 'Apr – Jun, Sep',
    avgTempC: 27,
    rating: 4.8,
    reviewCount: 2277,
    vibes: ['waterfalls', 'plumeria', 'longboards'],
    seed: 15,
  },
  {
    id: 'd-lisbon',
    name: 'Comporta',
    region: 'Alentejo',
    country: 'Portugal',
    blurb: 'Rice paddies, pine forest and eleven miles of empty Atlantic beach an hour from Lisbon.',
    nightlyFrom: 180,
    flightHours: 12,
    bestMonths: 'Jun – Sep',
    avgTempC: 25,
    rating: 4.6,
    reviewCount: 890,
    vibes: ['empty beaches', 'pine forest', 'thatched roofs'],
    seed: 55,
  },
  {
    id: 'd-bali',
    name: 'Sidemen',
    region: 'Bali',
    country: 'Indonesia',
    blurb: 'Terraced rice valleys under a volcano, frangipani everywhere, and mornings full of mist.',
    nightlyFrom: 85,
    flightHours: 21,
    bestMonths: 'Apr – Oct',
    avgTempC: 28,
    rating: 4.7,
    reviewCount: 1622,
    vibes: ['rice terraces', 'frangipani', 'volcano views'],
    seed: 68,
  },
  {
    id: 'd-cartagena',
    name: 'Cartagena',
    region: 'Bolívar',
    country: 'Colombia',
    blurb: 'A walled old town painted in mango and rose, with bougainvillea spilling off the balconies.',
    nightlyFrom: 120,
    flightHours: 8,
    bestMonths: 'Dec – Apr',
    avgTempC: 31,
    rating: 4.6,
    reviewCount: 1988,
    vibes: ['bougainvillea', 'colonial streets', 'rooftop bars'],
    seed: 33,
  },
  {
    id: 'd-byron',
    name: 'Byron Bay',
    region: 'New South Wales',
    country: 'Australia',
    blurb: 'Long right-hand point breaks, a lighthouse walk at dawn, and a very committed juice scene.',
    nightlyFrom: 200,
    flightHours: 17,
    bestMonths: 'Sep – Nov, Mar – May',
    avgTempC: 26,
    rating: 4.5,
    reviewCount: 1455,
    vibes: ['point break', 'lighthouse walk', 'markets'],
    seed: 81,
  },
  {
    id: 'd-cinque',
    name: 'Monterosso',
    region: 'Cinque Terre',
    country: 'Italy',
    blurb: 'The only one of the five with a real beach, plus anchovies and a very cold white wine.',
    nightlyFrom: 175,
    flightHours: 14,
    bestMonths: 'May – Jun, Sep',
    avgTempC: 25,
    rating: 4.6,
    reviewCount: 2640,
    vibes: ['coastal trail', 'pastel houses', 'anchovies'],
    seed: 92,
  },
  {
    id: 'd-zanzibar',
    name: 'Paje',
    region: 'Zanzibar',
    country: 'Tanzania',
    blurb: 'Turquoise shallows that go out forever, kite surfers, and frangipani in every doorway.',
    nightlyFrom: 95,
    flightHours: 22,
    bestMonths: 'Jun – Oct',
    avgTempC: 29,
    rating: 4.6,
    reviewCount: 1120,
    vibes: ['turquoise shallows', 'kitesurfing', 'spice farms'],
    seed: 47,
  },
]
